### PR TITLE
Get layer names, display RGBA channels from given layer

### PR DESCRIPTION
**Pull request by usakhelo**
Hi,
This is my attempt to handle loading channels by layer name (issue #53). It's different from original `ImfChannelList.h` implementation because I tried not to introduce new classes like iterator and such.

I updated tinyexr.h library and `exrview` example. `exrview` prints out layer names and accepts layer name command line argument.

There are certainly cases where the implementation can fail, like channels with names different from RGBA, or with number of channels in the layer less than 3 and so on.

Please let me know what you think and thanks for review,
Sergo.

### CODE REVIEW

**Comment by syoyo** [comment]
Awesome!

But it breaks existing `LoadEXR` API. I'm considering to  introduce new API something like `LoadEXRWithLayers` with your changes.

Also, do you have small .exr file with layer information for unit testing?

**Comment by usakhelo** [comment]
You're right, I didn't think about breaking API. Sorry.
I took small multilayer exr file from this conversation: https://github.com/godotengine/godot/issues/23723

**Comment by syoyo** [comment]
Added flaga.exr to `test/unit/regression`, use `LoadEXRWithLayers` and fixes some compilation error in this branch:

https://github.com/syoyo/tinyexr/tree/usakhelo-master

But the code fails when loading EXR(e.g. asakusa.exr)  with `layername = NULL`. @usakhelo please check the code? (also, adding unit test code is also appreciated)

**Comment by usakhelo** [comment]
I'll check @syoyo.

**Comment by usakhelo** [comment]
@syoyo what should happen when passed layer is not found? Should opening fail or quietly open first available RGB channels (current behaviour)?

**Comment by usakhelo** [comment]
Hi @syoyo I fixed the build and added test cases. One test case is checking `tinyexr` namespace functions. I'm not sure if it's needed or not. Feel free to remove that section.

**Comment by syoyo** [comment]
> @syoyo what should happen when passed layer is not found? Should opening fail or quietly open first available RGB channels (current behaviour)?

I think it is better to return error code such like `TINYEXR_LAYER_NOT_FOUND` when the name of layer is given but the layer is not found in .exr

**Comment by syoyo** [comment]
- Introduced new error code `TINYEXR_ERROR_LAYER_NOT_FOUND`
- Fixes memory leaks

Then things goes well, so merged!

**Pull request merged**
